# Generated by Django 4.0.1 on 2022-01-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesdropdown',
            name='stories',
            field=models.CharField(choices=[('askstories', 'Ask stories'), (None, 'Show stories'), ('newstories', 'New stories'), ('jobstories', 'Job stories')], default='newstories', max_length=15),
        ),
    ]
