# Generated by Django 4.0.1 on 2022-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_alter_storiesdropdown_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='descendants',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='kids',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='text',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='text',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='kids',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='text',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='descendants',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='kids',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='text',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ask',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storiesdropdown',
            name='stories',
            field=models.CharField(choices=[('askstories', 'Ask stories'), ('showstories', 'Show stories'), ('newstories', 'New stories'), ('jobstories', 'Job stories')], default='newstories', max_length=15),
        ),
    ]
