# Generated by Django 4.0.1 on 2022-02-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0004_rename_stories_storiesdropdown_newstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='s_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='s_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='s_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='s_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
