# Generated by Django 4.0.1 on 2022-02-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0005_alter_ask_s_id_alter_job_s_id_alter_new_s_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoriesDropDown',
        ),
    ]
